services:
  bros2_helloros:
    image: bros2/ros2-humble:latest
    container_name: bros2_helloros
    command: bash -lc "sleep infinity"
    working_dir: /workspace
    tty: true
    volumes:
      - "/Users/noahhathout/BROS2/Projects/hello_ros/workspace:/workspace"
    ports:
      - "9090:9090"
